// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllOpenedFiles() {
  return window['go']['application']['App']['AllOpenedFiles']();
}

export function ChangeSelectedFile(arg1) {
  return window['go']['application']['App']['ChangeSelectedFile'](arg1);
}

export function ListSelectedItems(arg1) {
  return window['go']['application']['App']['ListSelectedItems'](arg1);
}

export function OpenListMdFile() {
  return window['go']['application']['App']['OpenListMdFile']();
}

export function SelectListItem(arg1, arg2) {
  return window['go']['application']['App']['SelectListItem'](arg1, arg2);
}
