// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function AllOpenedFiles():Promise<application.OpenedFiles>;

export function ChangeSelectedFile(arg1:string):Promise<void>;

export function ChangeViewMode(arg1:string,arg2:application.ViewMode):Promise<void>;

export function Exit():Promise<void>;

export function ListSelectedItems(arg1:string):Promise<Array<string>>;

export function OpenListMdFile():Promise<void>;

export function SelectListItem(arg1:string,arg2:string):Promise<void>;

export function ToggleMaximize():Promise<void>;
