// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {listmd} from '../models';

export function OpenListMdFile():Promise<listmd.ListMd>;
