// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenListMdFile() {
  return window['go']['application']['App']['OpenListMdFile']();
}
